export const projects = [
  {
    title: "Text to Image with DALL·E - 2",
    subtitle: "React.js",
    description:
      "This App uses Open AI's publicly available API to generate a user specified image after user provides a prompt. It is responsive, have a gallery to showcase few amazing works generated by this AI.",
    image: "./dallE.png",
    link: "https://timely-bonbon-29cb3f.netlify.app/",
  },
  {
    title: "Food Order App",
    subtitle: "React.js",
    description:
      "Website reimagined for my favorite South Indian restaurant. It is responsive, have cart overlay and complete integration of state management.",
    image: "./foodApp.png",
    link: "https://cozy-axolotl-115da8.netlify.app/",
  },
  {
    title: "Todo App",
    subtitle: "React Hooks and TypeScript",
    description:
      "Todo App is one of the most utilised tool on any personal device. In this app, user can edit, check complete or delete list items. On a scaled up version I would love to build it as a Kanban Board. (It's in my Todos)",
    image: "./todo.png",
    link: "https://rococo-sable-466fde.netlify.app/",
  },
  {
    title: "Many more learning steps...",
    subtitle: "React.js, Vanilla JS, JQuery, Bootstrap",
    description:
      "I have worked on many projects in my learning process, most of them were me trying to replicate some cool small features and some were for completing my certifications.",
    image: "./Codepen.png",
    link: "https://codepen.io/nalini793",
  },
];
export const blogs = [
  {
    name: "How Facebook designed the like button",
    quote: `Excerpts from the book You Are Not Expected to Understand This: How 26 Lines of Code Changed the World.`,
    url: "https://www.fastcompany.com/90780140/the-inside-story-of-how-facebook-designed-the-like-button-and-made-social-media-into-a-popularity-contest",
  },
  {
    name: "Early career advice",
    quote: `This blogpost provides very concise and valuable advices and things to think through as you are moving forward in your career.`,
    url: "https://www.celinehh.com/early-career-advice",
  },
  {
    name: "Half Loaf Bread : a search engine",
    quote: `To quote the creator of this webapp: "I love bread but I don't want to be eating 20 slices in 3 days. It shouldn't be so hard to find half-loaves of bread. They should be available more abundantly."`,
    url: "https://halfloafnear.me/",
  },
  {
    name: "In defense of linked lists",
    quote: `A node pointing to itself is the most self centered thing I can imagine in computing: an ideal representation of the more vulgar infinite loop.`,
    url: "http://antirez.com/news/138",
  },

  {
    name: "Drowning in Problems",
    quote:
      "Need a crushing reminder of the frailty and futility of life? Markus “Notch” Persson (the creator of Minecraft) has your back. His web-based experience Drowning in Problems does a pretty fine job of making sure you don't forget. It provides a bleak life experience, starting with creating a body and a life, through to the inevitability of death.",
    url: "http://game.notch.net/drowning/#",
  },
  {
    name: "Little Languages Are The Future Of Programming",
    quote: `Little languages are at the opposite end of the power spectrum from C: Not only is the architecture of the computer abstracted away, but some of these languages also limit the kinds of program you can express—they’re Turing-incomplete by design. This might sound awfully limiting, but in fact it opens up a whole new dimension of possibilities for optimization and static analysis.`,
    url: "https://chreke.com/little-languages.html",
  },

  // {
  //   name: "What is the most impactful thing you've built?",
  //   quote: `This is a super interesting HackerNews discussion thread.`,
  //   url: "https://news.ycombinator.com/item?id=33659852",
  // },
  // {
  //   name: "Diátaxis: A systematic framework for technical documentation authoring.",
  //   quote: `The Diátaxis framework aims to solve the problem of structure in technical documentation. It adopts a systematic approach to understanding the needs of documentation users in their cycle of interaction with a product.`,
  //   url: "https://diataxis.fr/",
  // },
  // {
  //   name: "Deepgram: Automatic Speech Recognition",
  //   quote: `Deepgram is the first AI speech API for transcription with human-level understanding. From high fidelity, single-speaker dictation to staticky, multi-speaker, acronym-heavy ground-to-space communications, Deepgram delivers accurate transcriptions you can actually read.`,
  //   url: "https://deepgram.com/",
  // },

  // {
  //   name: "TourGuide JS",
  //   quote: `TourGuide is a Javascript library written for creating user tours and on-boarding steps for your apps."`,
  //   url: "https://github.com/sjmc11/tourguide-js",
  // },
];
export const testimonials = [
  {
    quote:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa quod necessitatibus quidem impedit facilis? Distinctio laboriosam veritatis recusandae minus. Voluptatum accusantium hic laudantium soluta ea sapiente cupiditate officia maiores itaque.",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    name: "Jesse Doe",
    company: "Wazon",
  },
  {
    quote:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa quod necessitatibus quidem impedit facilis? Distinctio laboriosam veritatis recusandae minus. Voluptatum accusantium hic laudantium soluta ea sapiente cupiditate officia maiores itaque.",
    image: "https://randomuser.me/api/portraits/men/94.jpg",
    name: "John Doe",
    company: "Fable.io",
  },
];

export const skills = [
  "Core Java",
  "JavaScript",
  "React",
  "TypeScript",
  "Node",
  "Express",
  "Mongo DB",
  "SQL",
  "SASS",
  "Bootstrap",
];
